name: bali-report
region: nyc
services:
- name: web
  source_dir: /
  github:
    repo: Murugan12963/bali-report
    branch: master
    deploy_on_push: true
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  health_check:
    http_path: /api/health
  envs:
  - key: NODE_ENV
    value: production
  - key: GOOGLE_ANALYTICS_ID
    value: G-K0VX8HVYE5
  - key: GOOGLE_ADSENSE_CLIENT
    value: ca-pub-3235214437727397
  - key: DISABLE_AI_AT_BUILD
    value: "false"
  - key: NEXT_PUBLIC_APP_URL
    value: "https://bali.report"
domains:
- domain: bali.report
- domain: www.bali.report
